### ISSUE TITLE
dataset of track3 download

### ISSUE THREAD

**Issue by zhouleidcc** [cw1204772/AIC2018_iamai#2]
hello, thank you for your excellent works. But, I can not get the dataset of track3.  Can you share your download dataset with me. Thanks in advance.

**Comment by cw1204772** [comment]
Hi, I can't share the dataset with you, unfortunately. The dataset belongs to NVIDIA AI Challenge and we, as a participating team, cannot distribute the dataset. I suggest you to contact [NVIDIA AI Challenge](https://www.aicitychallenge.org/) for getting the dataset. :slightly_smiling_face:
