### ISSUE TITLE
Evaluate CNN on VeRi

### ISSUE THREAD

**Issue by susuml** [cw1204772/AIC2018_iamai#5]
Hi!
 I have train my own cnn model ,and I want to evaluate it on VeRi. But I don't find the VeRi_gallery_info.txt in the dataset VeRi. So can you show me how to make a VeRi_gallery_info.txt ?

**Comment by cw1204772** [comment]
VeRi_gallery_info.txt does not exist in the VeRi dataset itself. 
We generate VeRi_gallery_info.txt using `ReID/ReID_CNN/setup.sh` to parse the image paths and labels into a universal format for training the CNN. 
You should look into `ReID/ReID_CNN/setup.sh`.
